### ISSUE TITLE
(3) Setup Jetson SSH + GitHub on Board

### ISSUE THREAD

**Issue by jordanpringle** [scotty914/GPGPU-Aerospace#11]

**Comment by pgaede** [comment]
sudo apt-get install git
sudo apt-get install openssh-server

We need to change the username of the machines to something like jetson1 and jeston2.. and the machine names to jet1 and jet2.. and set passwords for each.

Also need to determine whether we will be using ssh keys, or a complex (enough) password.

https://help.ubuntu.com/community/SSH/OpenSSH/Configuring
